# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2015, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by Shampoohat library 0.0.1 on 2015-06-08 10:25:46.

require 'criteo_api/errors'

module CriteoApi; module V201010; module AdvertiserService
  class AdvertiserServiceRegistry
    ADVERTISERSERVICE_METHODS = {:client_login=>{:input=>[], :output=>{:name=>"", :fields=>[]}}, :partner_login=>{:input=>[], :output=>{:name=>"", :fields=>[]}}, :get_account=>{:input=>[], :output=>{:name=>"", :fields=>[]}}, :get_campaigns=>{:input=>[], :output=>{:name=>"", :fields=>[]}}, :mutate_campaigns=>{:input=>[], :output=>{:name=>"", :fields=>[]}}, :get_categories=>{:input=>[], :output=>{:name=>"", :fields=>[]}}, :mutate_categories=>{:input=>[], :output=>{:name=>"", :fields=>[]}}, :get_budgets=>{:input=>[], :output=>{:name=>"", :fields=>[]}}, :schedule_report_job=>{:input=>[], :output=>{:name=>"", :fields=>[]}}, :get_job_status=>{:input=>[], :output=>{:name=>"", :fields=>[]}}, :get_report_download_url=>{:input=>[], :output=>{:name=>"", :fields=>[]}}, :get_statistics_last_update=>{:input=>[], :output=>{:name=>"", :fields=>[]}}}
    ADVERTISERSERVICE_TYPES = {:AdvertiserAccount=>{:fields=>[]}, :apiHeader=>{:fields=>[]}, :CampaignSelectors=>{:fields=>[]}, :ArrayOfInt=>{:fields=>[]}, :ArrayOfCampaignStatus=>{:fields=>[]}, :ArrayOfBiddingStrategy=>{:fields=>[]}, :ArrayOfCampaign=>{:fields=>[]}, :campaign=>{:fields=>[]}, :bidInformation=>{:fields=>[]}, :CPCBid=>{:fields=>[]}, :CPABid=>{:fields=>[]}, :ArrayOfCategoryBid=>{:fields=>[]}, :categoryBid=>{:fields=>[]}, :ArrayOfCampaignMutate=>{:fields=>[]}, :campaignMutate=>{:fields=>[]}, :mutate=>{:fields=>[]}, :ArrayOfCampaignMutateJobResponse=>{:fields=>[]}, :campaignMutateJobResponse=>{:fields=>[]}, :JobResponse=>{:fields=>[]}, :ApiExceptionData=>{:fields=>[]}, :ArrayOfApiError=>{:fields=>[]}, :apiError=>{:fields=>[]}, :CategorySelectors=>{:fields=>[]}, :ArrayOfCategory=>{:fields=>[]}, :category=>{:fields=>[]}, :ArrayOfCategoryMutate=>{:fields=>[]}, :categoryMutate=>{:fields=>[]}, :ArrayOfCategoryMutateJobResponse=>{:fields=>[]}, :categoryMutateJobResponse=>{:fields=>[]}, :BudgetSelectors=>{:fields=>[]}, :ArrayOfBudget=>{:fields=>[]}, :budget=>{:fields=>[]}, :ReportJob=>{:fields=>[]}, :ArrayOfReportColumn=>{:fields=>[]}, :ReportSelector=>{:fields=>[]}, :ReportJobResponse=>{:fields=>[]}, :ArrayOfStatUpdate=>{:fields=>[]}, :StatUpdate=>{:fields=>[]}, :CampaignStatus=>{:fields=>[]}, :biddingStrategy=>{:fields=>[]}, :OperationMutate=>{:fields=>[]}, :JobStatus=>{:fields=>[]}, :ApiExceptionErrorCode=>{:fields=>[]}, :ApiErrorCode=>{:fields=>[]}, :ReportColumn=>{:fields=>[]}, :ReportType=>{:fields=>[]}, :AggregationType=>{:fields=>[]}, :StatType=>{:fields=>[]}}
    ADVERTISERSERVICE_NAMESPACES = []

    def self.get_method_signature(method_name)
      return ADVERTISERSERVICE_METHODS[method_name.to_sym]
    end

    def self.get_type_signature(type_name)
      return ADVERTISERSERVICE_TYPES[type_name.to_sym]
    end

    def self.get_namespace(index)
      return ADVERTISERSERVICE_NAMESPACES[index]
    end
  end
end; end; end
